# 激光雷达扫描(scan)
- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  # 官方标准写法：使用 _name 后缀
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS
  publisher_options:
    qos:
      reliability: "best_effort"  # 解决 WSL2 丢包

# 运动控制指令(cmd_vel)
- ros_topic_name: "/cmd_vel"
  gz_topic_name: "/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ

# 关节状态(joint_states)
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/maze_world/model/my_cool_robot/joint_state" # 注意该路径可能随世界名称改变
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

# 里程计数据(odom)
- ros_topic_name: "/odom"
  gz_topic_name: "/odom"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"
  direction: GZ_TO_ROS

# 坐标系变换桥接(tf)
- ros_topic_name: "/tf"
  gz_topic_name: "/model/my_cool_robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

# 时钟同步(clock)
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS