slam_toolbox:
  ros__parameters:

    # 1. 坐标系配置 (必须与你的 URDF 匹配)
    odom_frame: my_cool_robot/odom
    map_frame: map
    base_frame: my_cool_robot/base_link
    scan_topic: /scan
    use_map_saver: true
    mode: mapping # 模式：建图

    # 2. 传感器参数
    # 你的雷达在 URDF 中 range max 是 12.0
    max_laser_range: 12.0
    min_laser_range: 0.1
    minimum_time_interval: 0.01
    transform_timeout: 0.2
    tf_buffer_duration: 30.
    stack_size_to_use: 40000000 
    enable_interactive_mode: true

    # 3. 算法处理参数 (保持默认即可)
    use_scan_matching: true
    use_scan_barycenter: true
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 10.0
    link_match_minimum_response_fine: 0.1  
    link_scan_maximum_distance: 1.5
    loop_search_maximum_distance: 3.0
    do_loop_closing: true
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45

    # 4. 关键：相关器参数
    correlation_search_space_dimension: 0.5
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    # 5. 优化器参数 (Ceres)
    optimize_step: 0.5
    optimize_every_n_nodes: 10
    resolution: 0.05 # 地图分辨率：5厘米